const DashboardProject = () => {
    return (
        <div className="bg-white shadow-md rounded-lg p-6 mb-4">
        <h2 className="text-3xl font-bold mb-2 text-center">Track all add-on product performance</h2>
        <div className="mb-4 text-center text-xl">
            <div>PowerBI, GCP BigQuery, Power Query</div>
        </div>

        <div className="grid grid-cols-3 gap-4 mb-4">
            <div className="flex justify-center">
                <img src="dashboard1.png" alt="Description 1" className="w-full h-auto rounded-lg" />
            </div>
            <div className="flex justify-center">
                <img src="dashboard2.png" alt="Description 2" className="w-full h-auto rounded-lg" />
            </div>
            <div className="flex justify-center">
                <img src="dashboard3.png" alt="Description 2" className="w-full h-auto rounded-lg" />
            </div>
        </div>

        <div className="mb-4">
            <span className="font-semibold">Context:</span>
            <div>To support the Growth Team in analyzing new add-on products such as PlentiCare (insurance), Return Without Cleaning, Games, and others, I took ownership of the entire development process for a data-driven solution. Leveraging <b>Power BI</b>, along with <b>Power Query</b> and <b>DAX</b>, and integrating data from a <b>BigQuery</b> database hosted on <b>Google Cloud Platform (GCP)</b>, I designed and implemented an intuitive and interactive dashboard. This solution enables straightforward analysis of the new data, empowering stakeholders to make informed decisions with ease. My leadership in this project ensured seamless functionality, clarity, and actionable insights, aligning with the team's objectives.</div>
        </div>
        <div className="mb-4">
            <span className="font-semibold">Research:</span>
            <div>The process began with in-depth research and engaging stakeholders through targeted questions to identify the KPIs and metrics most relevant to their needs. Recognizing that the tool would primarily be used by non-technical users, it was essential to ensure the analytics solution was both concise and user-friendly. Initial statistics on the add-on products revealed a high adoption rate, with customers frequently purchasing these offerings. This insight underscored the urgency of delivering the tool promptly to provide actionable insights and better understand the growth potential of this product category.</div>
        </div>
        <div className="mb-4">
            <span className="font-semibold">Approach:</span>
            <div>I promptly began by designing a <b>KPI dashboard</b>, focusing on key indicators such as:
            <ul>
                <li>- Number of Orders This Week vs. Previous Week</li>
                <li>- Total Revenue Generated by Each Product</li>
            </ul>
                These metrics provided a foundational understanding of the problem and allowed stakeholders to quickly grasp the overall performance trends.</div>
            <div>To offer deeper insights, I developed a dedicated PlentiCare performance tracking page, as it represented the most profitable segment. This page highlighted critical analytics, including the effectiveness of different price points, most frequently purchased products with insurance, and other key performance metrics. This dual-page approach ensured both a broad overview and detailed analysis, addressing diverse stakeholder needs effectively.</div>
        </div>
        <div className="mb-4">
            <span className="font-semibold">Features:</span>
            <div>Developed an interactive, intuitive, and visually appealing Power BI dashboard to track the performance of each add-on product individually, while also providing a comprehensive view of the aggregated performance across the entire product portfolio.</div>
        </div>
        <div className="mb-4">
            <span className="font-semibold">Outcome:</span>
            <div>The dashboard provided actionable insights that transformed decision-making. The data revealed that the majority of insurance purchases were made by B2B clients, highlighting a critical target audience for this product. Additionally, the analysis uncovered that lower price points were leading to losses, prompting a strategic adjustment to increase prices. This change not only addressed profitability concerns but also aligned the product's pricing strategy with its value proposition. These insights underscored the importance of data-driven decisions and demonstrated the effectiveness of the dashboard in guiding business growth.</div>
        </div>
        </div>
    );
};

export default DashboardProject;